// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import { IColumn } from '@fluentui/react';
import { repoListColumns } from '../../strings/Strings';

// Defines the columns in a repository list
export const repositoryColumns: IColumn[] = [
  {
    key: 'name',
    name: repoListColumns.name,
    fieldName: 'name',
    minWidth: 200,
    maxWidth: 300,
    isRowHeader: true,
    isResizable: true,
    isSorted: true,
    isSortedDescending: false,
  },
  {
    key: 'owners',
    name: repoListColumns.owners,
    fieldName: 'owners',
    minWidth: 100,
    maxWidth: 150,
    isResizable: true,
    isMultiline: true,
  },
  {
    key: 'status',
    name: repoListColumns.status,
    fieldName: 'repositoryStatus',
    minWidth: 100,
    maxWidth: 150,
    isResizable: true,
  },
  {
    key: 'lastUpdated',
    name: repoListColumns.lastUpdated,
    fieldName: 'lastUpdated',
    minWidth: 100,
    maxWidth: 150,
    isResizable: true,
  },
  {
    key: 'identityLibs',
    name: repoListColumns.identityLibs,
    fieldName: 'identityStatus',
    minWidth: 100,
    maxWidth: 150,
    isResizable: true,
  },
  {
    key: 'graphSdks',
    name: repoListColumns.graphSdks,
    fieldName: 'graphStatus',
    minWidth: 100,
    maxWidth: 150,
    isResizable: true,
  },
  {
    key: 'securityAlertCount',
    name: repoListColumns.securityAlerts,
    fieldName: 'securityAlerts',
    minWidth: 75,
    maxWidth: 100,
    isResizable: true,
  },
  {
    key: 'pullRequestCount',
    name: repoListColumns.openPRs,
    fieldName: 'pullRequests',
    minWidth: 75,
    maxWidth: 100,
    isResizable: true,
  },
  {
    key: 'issueCount',
    name: repoListColumns.openIssues,
    fieldName: 'issues',
    minWidth: 75,
    maxWidth: 100,
    isResizable: true,
  },
  {
    key: 'forkCount',
    name: repoListColumns.forks,
    fieldName: 'forks',
    minWidth: 75,
    maxWidth: 100,
    isResizable: true,
  },
  {
    key: 'starsCount',
    name: repoListColumns.stars,
    fieldName: 'starGazers',
    minWidth: 75,
    maxWidth: 100,
    isResizable: true,
  },
  {
    key: 'viewCount',
    name: repoListColumns.views,
    fieldName: 'views',
    minWidth: 75,
    maxWidth: 100,
    isResizable: true,
  },
  {
    key: 'language',
    name: repoListColumns.language,
    fieldName: 'language',
    minWidth: 75,
    maxWidth: 100,
    isResizable: true,
    isMultiline: true,
  },
  {
    key: 'featureArea',
    name: repoListColumns.featureArea,
    fieldName: 'featureArea',
    minWidth: 100,
    maxWidth: 150,
    isResizable: true,
    isMultiline: true,
  },
];
